import { MRT_ColumnDef } from 'material-react-table';
import { useMemo } from 'react';

import { ShowComentarioCRMModal } from '../modal';
import { emptyCellOneLevel } from '@/shared/utils';
import { TABLE_CONSTANTS } from '@/shared/constants';
import {
  CRM_cambio_domicilio,
  CRM_cambio_plan,
  CRM_contratar,
  CRM_migracion,
  CRM_soporte_tecnico,
  CRM_suspension,
} from '@/shared/interfaces';

export const useColumnsHistoryYS = () => {
  const soportetecnicoYSColumns = useMemo<MRT_ColumnDef<CRM_soporte_tecnico>[]>(
    () => [
      {
        accessorKey: 'codigo',
        header: 'Codigo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'codigo'),
      },
      {
        accessorKey: 'coleccion',
        header: 'coleccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'coleccion'),
      },
      {
        accessorKey: 'cedula',
        header: 'Cedula',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'cedula'),
      },
      {
        accessorKey: 'usuarioacciones',
        header: 'Usuario Acciones',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'usuarioacciones'),
      },
      {
        accessorKey: 'direccion',
        header: 'Direccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'direccion'),
      },
      {
        accessorKey: 'estadocliente',
        header: 'Estado Cliente',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'estadocliente'),
      },
      {
        accessorKey: 'unidadnegocio',
        header: 'Unidad de negocio',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'unidadnegocio'),
      },
      {
        accessorKey: 'nombres',
        header: 'Nombres',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'nombres'),
      },
      {
        accessorKey: 'tipoproblema',
        header: 'Tipo Problema',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'tipoproblema'),
      },
      {
        accessorKey: 'descripciontipootro',
        header: 'Descripción tipo otro',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'descripciontipootro'),
      },
      {
        accessorKey: 'telefonos',
        header: 'Telefonos',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'telefonos'),
      },
      {
        accessorKey: 'observacion',
        header: 'Observaciones',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'observacion'),
      },
      {
        accessorKey: 'motivo',
        header: 'Motivo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'motivo'),
      },
      {
        accessorKey: 'comentarios',
        header: 'COMENTARIOS',
        enableColumnFilter: false,
        size: TABLE_CONSTANTS.COLUMN_WIDTH_SMALL,
        Cell: ({ row }) => {
          return <ShowComentarioCRMModal Arrays={row.original.comentarios} />;
        },
      },
    ],
    [],
  );
  const cambioPlanYSColumns = useMemo<MRT_ColumnDef<CRM_cambio_plan>[]>(
    () => [
      {
        accessorKey: 'codigo',
        header: 'Codigo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'codigo'),
      },
      {
        accessorKey: 'coleccion',
        header: 'coleccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'coleccion'),
      },
      {
        accessorKey: 'cedula',
        header: 'Cedula',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'cedula'),
      },

      {
        accessorKey: 'direccion',
        header: 'Direccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'direccion'),
      },
      {
        accessorKey: 'estadocliente',
        header: 'Estado Cliente',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'estadocliente'),
      },

      {
        accessorKey: 'nombres',
        header: 'Nombres',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'nombres'),
      },
      {
        accessorKey: 'motivo',
        header: 'Motivo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'motivo'),
      },
      {
        accessorKey: 'comentarios',
        header: 'COMENTARIOS',
        enableColumnFilter: false,
        size: TABLE_CONSTANTS.COLUMN_WIDTH_SMALL,
        Cell: ({ row }) => {
          return <ShowComentarioCRMModal Arrays={row.original.comentarios} />;
        },
      },
    ],
    [],
  );
  const cambioDomicilioYSColumns = useMemo<
    MRT_ColumnDef<CRM_cambio_domicilio>[]
  >(
    () => [
      {
        accessorKey: 'codigo',
        header: 'Codigo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'codigo'),
      },
      {
        accessorKey: 'coleccion',
        header: 'coleccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'coleccion'),
      },
      {
        accessorKey: 'cedula',
        header: 'Cedula',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'cedula'),
      },
      {
        accessorKey: 'direccion',
        header: 'Direccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'direccion'),
      },
      {
        accessorKey: 'estadocliente',
        header: 'Estado Cliente',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'estadocliente'),
      },
      {
        accessorKey: 'unidadnegocio',
        header: 'Unidad de negocio',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'unidadnegocio'),
      },
      {
        accessorKey: 'nombres',
        header: 'Nombres',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'nombres'),
      },
      {
        accessorKey: 'telefonos',
        header: 'Telefonos',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'telefonos'),
      },
      {
        accessorKey: 'comentarios',
        header: 'COMENTARIOS',
        enableColumnFilter: false,
        size: TABLE_CONSTANTS.COLUMN_WIDTH_SMALL,
        Cell: ({ row }) => {
          return <ShowComentarioCRMModal Arrays={row.original.comentarios} />;
        },
      },
    ],
    [],
  );
  const contratarYSColumns = useMemo<MRT_ColumnDef<CRM_contratar>[]>(
    () => [
      {
        accessorKey: 'codigo',
        header: 'Codigo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'codigo'),
      },
      {
        accessorKey: 'coleccion',
        header: 'coleccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'coleccion'),
      },
      {
        accessorKey: 'cedula',
        header: 'Cedula',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'cedula'),
      },
      {
        accessorKey: 'usuarioacciones',
        header: 'Usuario Acciones',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'usuarioacciones'),
      },
      {
        accessorKey: 'direccion',
        header: 'Direccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'direccion'),
      },
      {
        accessorKey: 'nombres',
        header: 'Nombres',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'nombres'),
      },
      {
        accessorKey: 'observacion',
        header: 'Observaciones',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'observacion'),
      },
      {
        accessorKey: 'comentarios',
        header: 'COMENTARIOS',
        enableColumnFilter: false,
        size: TABLE_CONSTANTS.COLUMN_WIDTH_SMALL,
        Cell: ({ row }) => {
          return <ShowComentarioCRMModal Arrays={row.original.comentarios} />;
        },
      },
    ],
    [],
  );
  const migracionYSColumns = useMemo<MRT_ColumnDef<CRM_migracion>[]>(
    () => [
      {
        accessorKey: 'codigo',
        header: 'Codigo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'codigo'),
      },
      {
        accessorKey: 'coleccion',
        header: 'coleccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'coleccion'),
      },
      {
        accessorKey: 'cedula',
        header: 'Cedula',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'cedula'),
      },
      {
        accessorKey: 'usuarioacciones',
        header: 'Usuario Acciones',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'usuarioacciones'),
      },
      {
        accessorKey: 'direccion',
        header: 'Direccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'direccion'),
      },
      {
        accessorKey: 'estadocliente',
        header: 'Estado Cliente',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'estadocliente'),
      },
      {
        accessorKey: 'unidadnegocio',
        header: 'Unidad de negocio',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'unidadnegocio'),
      },
      {
        accessorKey: 'nombres',
        header: 'Nombres',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'nombres'),
      },
      {
        accessorKey: 'tipoproblema',
        header: 'Tipo Problema',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'tipoproblema'),
      },
      {
        accessorKey: 'descripciontipootro',
        header: 'Descripción tipo otro',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'descripciontipootro'),
      },
      {
        accessorKey: 'telefonos',
        header: 'Telefonos',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'telefonos'),
      },
      {
        accessorKey: 'observacion',
        header: 'Observaciones',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'observacion'),
      },
      {
        accessorKey: 'motivo',
        header: 'Motivo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'motivo'),
      },
      {
        accessorKey: 'comentarios',
        header: 'COMENTARIOS',
        enableColumnFilter: false,
        size: TABLE_CONSTANTS.COLUMN_WIDTH_SMALL,
        Cell: ({ row }) => {
          return <ShowComentarioCRMModal Arrays={row.original.comentarios} />;
        },
      },
    ],
    [],
  );
  const suspensionYSColumns = useMemo<MRT_ColumnDef<CRM_suspension>[]>(
    () => [
      {
        accessorKey: 'codigo',
        header: 'Codigo',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'codigo'),
      },
      {
        accessorKey: 'coleccion',
        header: 'coleccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'coleccion'),
      },
      {
        accessorKey: 'cedula',
        header: 'Cedula',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'cedula'),
      },
      {
        accessorKey: 'direccion',
        header: 'Direccion',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'direccion'),
      },
      {
        accessorKey: 'estadocliente',
        header: 'Estado Cliente',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'estadocliente'),
      },
      {
        accessorKey: 'unidadnegocio',
        header: 'Unidad de negocio',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'unidadnegocio'),
      },
      {
        accessorKey: 'nombres',
        header: 'Nombres',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'nombres'),
      },
      {
        accessorKey: 'motivo_suspension',
        header: 'Motivo Suspensión',
        size: TABLE_CONSTANTS.COLUMN_WIDTH_MEDIUM,
        enableColumnFilter: true,
        enableSorting: true,
        Cell: ({ row }) => emptyCellOneLevel(row, 'motivo'),
      },
      {
        accessorKey: 'comentarios',
        header: 'COMENTARIOS',
        enableColumnFilter: false,
        size: TABLE_CONSTANTS.COLUMN_WIDTH_SMALL,
        Cell: ({ row }) => {
          return <ShowComentarioCRMModal Arrays={row.original.comentarios} />;
        },
      },
    ],
    [],
  );

  return {
    soportetecnicoYSColumns,
    cambioPlanYSColumns,
    cambioDomicilioYSColumns,
    contratarYSColumns,
    migracionYSColumns,
    suspensionYSColumns,
  };
};
