export enum SidenavModulesEnum {
  ADMIN_PAISES = 'ADMIN.PAISES',
  ADMIN_PROVINCIAS = 'ADMIN.PROVINCIAS',
  ADMIN_CIUDADES = 'ADMIN.CIUDADES',
  ADMIN_ZONAS = 'ADMIN.ZONAS',
  ADMIN_SECTORES = 'ADMIN.SECTORES',
  ADMIN_AREAS = 'ADMIN.AREAS',
  ADMIN_DEPARTAMENTOS = 'ADMIN.DEPARTAMENTOS',
  ADMIN_CANAL_VENTA = 'ADMIN.CANAL_VENTA',
  ADMIN_EMPRESAS = 'ADMIN.EMPRESAS',
  ADMIN_IVA = 'ADMIN.IVA',
  ADMIN_PARAMETRO_SISTEMA = 'ADMIN.PARAMETRO_SISTEMA',

  NOMINA_CARGO = 'NOMINA.CARGO',
  NOMINA_EMPLEADO = 'NOMINA.EMPLEADO',

  SERVICIOS_PLAN = 'SERVICIOS.PLAN',

  COMERCIAL_PROMOCIONES = 'COMERCIAL.PROMOCIONES',
  COMERCIAL_SOLICITUD_SERVICIO = 'COMERCIAL.SOLICITUD_SERVICIO',
  COMERCIAL_PREVENTA = 'COMERCIAL.PREVENTA',

  SUPERVISIONCOMERCIAL_SOLICITUD_DESBLOQUEO_VENTAS = 'SUPERVISIONCOMERCIAL.SOLICITUD_DESBLOQUEO_VENTAS',

  USUARIOS_USUARIOS = 'USUARIOS.USUARIOS',
  USUARIOS_GRUPOS = 'USUARIOS.GRUPOS',
}
