export * from './bodega';
export * from './cuenta-contable';
export * from './ingreso-material';
export * from './egreso-material';
export * from './modelo-inventario';
export * from './motivo-egreso';
export * from './motivo-ingreso';
export * from './motivo-transferencia';
export * from './movimiento-material';
export * from './solicitud-compra';
export * from './solicitud-devolucion';
export * from './solicitud-material';
export * from './solicitud-transferencia-material';
export * from './transferencia-material';

export * from './categoria-producto.schema';
export * from './producto.schema';
export * from './ubicacion-producto.schema';
export * from './ubicacion.schema';
